#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Command {
  CancelSearch,
  CloseComments,
  HideHelp,
  None,
  OpenCommentLink,
  OpenComments,
  OpenCurrentInBrowser,
  PageDown,
  PageUp,
  Quit,
  SelectFirst,
  SelectNext,
  SelectPrevious,
  ShowHelp,
  StartSearch,
  SubmitSearch,
  SwitchTabLeft,
  SwitchTabRight,
  ToggleBookmark,
}
